// <auto-generated />
using System;
using ChatBotPrime.Infra.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChatBotPrime.Infra.Data.EF.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20200713132003_Messagechange")]
    partial class Messagechange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChatBotPrime.Core.Data.Model.BasicCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Cooldown")
                        .HasColumnType("time");

                    b.Property<bool>("IsAllowedToRun")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastRun")
                        .HasColumnType("datetime2");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BasicCommands");
                });

            modelBuilder.Entity("ChatBotPrime.Core.Data.Model.BasicMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BasicMessages");
                });

            modelBuilder.Entity("ChatBotPrime.Core.Data.Model.CommandAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Word")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("commandId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("commandId");

                    b.ToTable("CommandAlias");
                });

            modelBuilder.Entity("ChatBotPrime.Core.Data.Model.MessageAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Word")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageAlias");
                });

            modelBuilder.Entity("ChatBotPrime.Core.Data.Model.CommandAlias", b =>
                {
                    b.HasOne("ChatBotPrime.Core.Data.Model.BasicCommand", "command")
                        .WithMany("Aliases")
                        .HasForeignKey("commandId");
                });

            modelBuilder.Entity("ChatBotPrime.Core.Data.Model.MessageAlias", b =>
                {
                    b.HasOne("ChatBotPrime.Core.Data.Model.BasicMessage", "Message")
                        .WithMany("Aliases")
                        .HasForeignKey("MessageId");
                });
#pragma warning restore 612, 618
        }
    }
}
